# Generated by Django 5.2.12 on 2026-03-22 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_donation_expense_delete_financerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDonationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bulk Upload', max_length=200)),
                ('list_image', models.ImageField(upload_to='bulk_donations/')),
                ('parsed_data', models.TextField(blank=True, help_text="Review and edit the extracted list here. Format: 'Name: Amount' (one per line).", null=True)),
                ('generate_donations', models.BooleanField(default=False, help_text='Check this box and save to generate individual Donation records from the parsed data above.')),
                ('is_processed', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
