# Generated by Django 5.2.12 on 2026-03-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bulkdonationupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdonationupload',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
