# Generated by Django 5.2.12 on 2026-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bulkdonationupload_is_deleted_donation_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdonationupload',
            name='data_file',
            field=models.FileField(blank=True, help_text='Upload CSV, Excel (.xlsx), or TXT file with your donor list.', null=True, upload_to='bulk_donations/files/'),
        ),
        migrations.AlterField(
            model_name='bulkdonationupload',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='bulk_donations/'),
        ),
    ]
