# Generated by Django 5.2.12 on 2026-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bulkdonationupload_data_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF receipt', null=True, upload_to='receipts/pdfs/'),
        ),
    ]
