# Generated by Django 5.2.12 on 2026-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_donation_receipt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdonationupload',
            name='master_receipts_pdf',
            field=models.FileField(blank=True, help_text='Combined Multi-Page PDF of all generated receipts', null=True, upload_to='receipts/bulk/'),
        ),
    ]
