# Generated by Django 5.2.12 on 2026-03-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bulkdonationupload_master_receipts_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkExpenseUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bulk Expenses Upload', max_length=200)),
                ('data_file', models.FileField(blank=True, help_text='Upload CSV, Excel (.xlsx), or TXT file with your expense list.', null=True, upload_to='bulk_expenses/files/')),
                ('parsed_data', models.TextField(blank=True, help_text="Review and edit the extracted list here. Format: 'Cost Description: Amount' (one per line).", null=True)),
                ('generate_expenses', models.BooleanField(default=False, help_text='Check this box and save to generate individual Expense records from the parsed data above.')),
                ('is_processed', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
