# Generated by Django 5.2.12 on 2026-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_bulkexpenseupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Due)'), ('CLEARED', 'Cleared (Paid)')], default='CLEARED', max_length=20),
        ),
    ]
